version: 1.2
workflows:
  - name: Mad4Hatter
    subclass: WDL
    primaryDescriptorPath: /Mad4Hatter.wdl
    readMePath: /Mad4Hatter.README.md
    testParameterFiles:
      - /Mad4Hatter.wdl

  - name: Mad4HatterQcOnly
    subclass: WDL
    primaryDescriptorPath: /Mad4HatterQcOnly.wdl
    readMePath: /Mad4HatterQcOnly.README.md
    testParameterFiles:
      - /Mad4HatterQcOnly.wdl

  - name: Mad4HatterPostProcessing
    subclass: WDL
    primaryDescriptorPath: /Mad4HatterPostProcessing.wdl
    readMePath: /Mad4HatterPostProcessing.README.md
    testParameterFiles:
      - /Mad4HatterPostProcessing.wdl